### ISSUE TITLE
Current teams branch build fails

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/gcc#16]
# Defect/Bug Report #

The title of the issue should start with `Defect:` followed by a
succinct title.

- GCC fork release tag or git hash: teams-20171128
- GCC version used to build this fork: 7.2.0
- Output of `uname -a`: `Linux sourcery-VirtualBox 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Machine architecture and number of physical cores: [Sourcery Institute virtual machine], 4 cores

## Observed Behavior ##
Here's the tail of the output:
```bash
g++ -fno-PIE -c  -DIN_GCC_FRONTEND -g -O2 -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -fno-common  -DHAVE_CONFIG_H -I. -Ifortran -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/fortran -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/../include -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/../libcpp/include -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/builds/gcc-teams-20171128/./gmp -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gmp -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/builds/gcc-teams-20171128/./mpfr/src -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/mpfr/src -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/mpc/src  -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/../libdecnumber -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/../libdecnumber/bid -I../libdecnumber -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/../libbacktrace -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/builds/gcc-teams-20171128/./isl/include -I/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/isl/include  -o fortran/array.o -MT fortran/array.o -MMD -MP -MF fortran/.deps/array.TPo /home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/fortran/array.c
/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/fortran/array.c: In function ‘match gfc_match_array_ref(gfc_array_ref*, gfc_array_spec*, int, int)’:
/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/fortran/array.c:237:8: error: ‘gfc_array_ref {aka struct gfc_array_ref}’ has no member named ‘team’
    ar->team = tmp;
        ^~~~
/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/fortran/array.c:238:4: error: ‘team_just_seen’ was not declared in this scope
    team_just_seen = true;
    ^~~~~~~~~~~~~~
/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/fortran/array.c:238:4: note: suggested alternative: ‘stat_just_seen’
    team_just_seen = true;
    ^~~~~~~~~~~~~~
    stat_just_seen
/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/fortran/array.c:241:15: error: ‘gfc_array_ref {aka struct gfc_array_ref}’ has no member named ‘team’
       if (ar->team && !team_just_seen)
               ^~~~
/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/fortran/array.c:241:24: error: ‘team_just_seen’ was not declared in this scope
       if (ar->team && !team_just_seen)
                        ^~~~~~~~~~~~~~
/home/rouson/Desktop/Builds/opencoarrays/prerequisites/downloads/gcc-teams-20171128/gcc/fortran/array.c:241:24: note: suggested alternative: ‘stat_just_seen’
       if (ar->team && !team_just_seen)
                        ^~~~~~~~~~~~~~
                        stat_just_seen
Makefile:1110: recipe for target 'fortran/array.o' failed
make[2]: *** [fortran/array.o] Error 1
make[2]: *** Waiting for unfinished jobs....
rm gcov.pod fsf-funding.pod gpl.pod cpp.pod gfdl.pod gcc.pod gcov-dump.pod gfortran.pod gcov-tool.pod
make[2]: Leaving directory '/home/rouson/Desktop/Builds/opencoarrays/prerequisites/builds/gcc-teams-20171128/gcc'
Makefile:4306: recipe for target 'all-gcc' failed
make[1]: *** [all-gcc] Error 2
make[1]: Leaving directory '/home/rouson/Desktop/Builds/opencoarrays/prerequisites/builds/gcc-teams-20171128'
Makefile:917: recipe for target 'all' failed
make: *** [all] Error 2
```
## Steps to Reproduce ##
```bash
git clone https://github.com/sourceryinstitute/opencoarrays
cd opencoarrays
./install.sh 
```
# Question #

@scrassmusen Does the above mean anything to you?

[links]:#
[Google]: https://www.google.com
[Stack Overflow]: https://stackoverflow.com
[fenced codeblocks]: https://help.github.com/articles/creating-and-highlighting-code-blocks/
[CONTRIBUTING.md]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[Helping Out]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md#helping-out
[Contributing to GCC]: https://gcc.gnu.org/contribute.html
 [Sourcery Institute virtual machine]: https://www.sourceryinstitute.org/store

**Comment by scrasmussen** [comment]
@rouson I pushed the changes that should have fixed the problems, I'm doing more testing before closing the issue. Sorry about that, yesterday I realized the merge hadn't worked properly and I started fixing it. Next time I'll properly test the merge and make a bug report so everyone knows what's going on.

**Comment by rouson** [comment]
No problem.  A common hit workflow is to have a “develop” branch that is kept free of known bugs and to branch off of that for experimental work.  Effectively, our teams branch is our develop branch so you’ve done the right thing to branch off of it forbyiue day to day work.  As long as you’re on your own branch, it’s less important to keep the branch building all the time and one thing love about for is that it increases the frequency with which people commit and push.  Pushing things that aren’t working is not at all a problem as long as those commits are on a branch not affecting others. In fact, it can be quite good to push things that aren’t working because it can be a way to get others’ feedback on how to solve problems. Testing before pushing becomes important when it’s time to merge into a branch that everyone else is using. Then you generate s pull request so others can see and test the work and the most important time to test us before merging the pull request.

**Comment by zbeekman** [comment]
FYI, this book looks pretty great. I just purchased a copy, and have read a few sections: https://github.com/GitInPractice/gitinpractice.github.io

**Comment by scrasmussen** [comment]
@rouson, thanks for explaining the workflow. I'll also check out @zbeekman's recommendation and read up on it more. I tried to do the original merge through the web interface, it didn't pick up all the changes that I thought it would and caused the problems. Lessons learned...

**Comment by rouson** [comment]
@scrasmussen I still can't install the teams branch.  The tail of the output is below. Strangely, the builds completes but the installation fails and it's not a permissions issue.

```bash
/usr/bin//install -c -m 644 b-header-vars /home/rouson/Desktop/Builds/opencoarrays/prerequisites/installations/gcc/teams-20171206/lib/gcc/x86_64-pc-linux-gnu/8.0.0/plugin/include/b-header-vars
make[2]: Leaving directory '/home/rouson/Desktop/Builds/opencoarrays/prerequisites/builds/gcc-teams-20171206/gcc'
make[2]: write error: stdout
Makefile:4390: recipe for target 'install-gcc' failed
make[1]: *** [install-gcc] Error 1
make[1]: Leaving directory '/home/rouson/Desktop/Builds/opencoarrays/prerequisites/builds/gcc-teams-20171206'
Makefile:2318: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by rouson** [comment]
Also, it seems that `team_number` is still missing.  That's  pretty fundamental component that I imagine most codes using teams will need.  Hopefully @afanfa can provide some advice regarding implementing it.  Issue #11 highlights this.  I worked on supporting team_number in a branch that I haven't maintained so I'm not sure it will be of much use.

**Comment by scrasmussen** [comment]
@rouson and I have both gotten the current teams branch to work so I'm closing the issue. The argument "--disable-werror" and the "lto" language option have been removed from the OpenCoarrays install script.
